DEBUG 2025-01-21 14:24:49.551 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-21 14:24:49.551 UTC: 	 Running on: Linux lxplus807.cern.ch 4.18.0-553.30.1.el8_10.x86_64 #1 SMP Fri Nov 15 03:46:25 EST 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-21 14:24:49.551 UTC: 	 Not using Singularity
DEBUG 2025-01-21 14:24:49.551 UTC: 	 Operating System: Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2025-01-21 14:24:49.551 UTC: 	 Executing command: 'status'
DEBUG 2025-01-21 14:24:49.551 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yeo/.crab3
ERROR 2025-01-21 14:24:49.552 UTC: 	 Error: crab_project/HToAATo4L_H750A1_22 is not a valid CRAB project directory.
ERROR 2025-01-21 14:24:49.552 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_project/HToAATo4L_H750A1_22 is not a valid CRAB project directory.
INFO 2025-01-21 14:24:49.560 UTC: 	 Log file is /afs/cern.ch/user/y/yeo/4l/24.10.08/CMSSW_13_0_13/src/ZprimeTo4l/MergedLepton/test/25.01.21/crab/HToAATo4L_H750A1_22/crab.log
DEBUG 2025-01-21 14:25:28.493 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-21 14:25:28.493 UTC: 	 Running on: Linux lxplus807.cern.ch 4.18.0-553.30.1.el8_10.x86_64 #1 SMP Fri Nov 15 03:46:25 EST 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-21 14:25:28.493 UTC: 	 Not using Singularity
DEBUG 2025-01-21 14:25:28.493 UTC: 	 Operating System: Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2025-01-21 14:25:28.493 UTC: 	 Executing command: 'status'
DEBUG 2025-01-21 14:25:28.493 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yeo/.crab3
ERROR 2025-01-21 14:25:28.494 UTC: 	 Error: crab_projects/HToAATo4L_H750A1_22 is not a valid CRAB project directory.
ERROR 2025-01-21 14:25:28.494 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/HToAATo4L_H750A1_22 is not a valid CRAB project directory.
INFO 2025-01-21 14:25:28.495 UTC: 	 Log file is /afs/cern.ch/user/y/yeo/4l/24.10.08/CMSSW_13_0_13/src/ZprimeTo4l/MergedLepton/test/25.01.21/crab/HToAATo4L_H750A1_22/crab.log
